version: 2.1

orbs:
  cplace: collaboration-factory/cplace@<< pipeline.parameters.cplace-orb-version >>

parameters:
  workflow_commit:
    type: boolean
    default: true
  cplace-orb-version:
    description: |
      The version of the orb to use.
      Used to allow integration testing of new orb versions.
      For production, the default should be used.
    type: string
    default: "1"

commands:
  shallow_checkout:
    description: "Checkout the code using a shallow clone"
    steps:
      - cplace/shallow_clone:
          clone_to_dir: .
          trace_log: false
  prepare_build_environment:
    description: "Prepares the build environment and installs java."
    steps:
      - run:
          name: "Prepare build environment"
          command: |
            set -e
            # sudo update-alternatives --set java /usr/lib/jvm/java-11-openjdk-amd64/jre/bin/java
            # sudo update-alternatives --set javac /usr/lib/jvm/java-11-openjdk-amd64/bin/javac
            # echo "export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64" >> $BASH_ENV
            java -version
            javac -version
jobs:
  build-and-test:
    machine:
      image: ubuntu-2004:202201-02
    parallelism: 1
    shell: /bin/bash --login
    environment:
      _JAVA_OPTIONS: -Xmx2048m -Djava.awt.headless="true"
    steps:
      - shallow_checkout
      - prepare_build_environment
      - run:
         name: "Build and test"
            command: |
              mvn -v
              mvn deploy -s .circleci/maven-settings.xml --fail-at-end
      - store_test_results:
          path: ~/target/surefire-reports
      - store_artifacts:
          path: ~/target/surefire-reports

workflows:
  version: 2
  commit:
    when: << pipeline.parameters.workflow_commit >>
    jobs:
      - build-and-test:
          name: "build"
          context: "cplace.jfrog.io"
